# Python Basics

### Question 1: How do you perform basic arithmetic operations in Python?

In [1]:
a=10
b=5
print(a+b)
print(a-b)
print(a*b)
print(a/b)

15
5
50
2.0


### Question 2: How do you implement a while loop to count to five?

In [2]:
count=1
while count<=5:
    print(count)
    count+=1

1
2
3
4
5


### Question 3: How do you use a for loop to iterate through a range of numbers?

In [3]:
for i in range(3):
    print(i)

0
1
2


### Question 4: How do you define a simple function with no parameters?

In [4]:
def greet():
    print("hello")
greet()

hello


### Question 5: How do you define a function that accepts arguments?

In [5]:
def add_numbers(x,y):
    return x+y
print(add_numbers(10,20))

30


### Question 6: How do you create a function with a default parameter value?

In [6]:
def power(base,exp=2):
    return base**exp
print(power(4))

16


### Question 7: How do you use a lambda function to square a number?

In [7]:
square=lambda x:x*x
print(square(6))

36


### Question 8: How do you append an element to a list?

In [8]:
items=[1,2,3]
items.append(4)
print(items)

[1, 2, 3, 4]


### Question 9: How do you remove a specific element from a list?

In [9]:
items=[1,2,3,4]
items.remove(2)
print(items)

[1, 3, 4]


### Question 10: How do you sort a list in ascending order?

In [10]:
nums=[5,2,8,1]
nums.sort()
print(nums)

[1, 2, 5, 8]


### Question 11: How do you reverse the elements in a list?

In [11]:
nums=[1,2,3]
nums.reverse()
print(nums)

[3, 2, 1]


### Question 12: How do you find the index of a specific element in a list?

In [12]:
chars=['a','b','c']
print(chars.index('b'))

1


### Question 13: How do you clear all elements from a list?

In [13]:
data=[1,2,3]
data.clear()
print(data)

[]


### Question 14: How do you count the occurrences of an item in a list?

In [14]:
vals=[1,2,2,3,2]
print(vals.count(2))

3


### Question 15: How do you convert two lists into a dictionary?

In [15]:
keys=['id','name']
values=[101,'Abdullah']
result=dict(zip(keys,values))
print(result)

{'id': 101, 'name': 'Abdullah'}


### Question 16: How do you convert a dictionary into a list of tuples?

In [16]:
info={'a':1,'b':2}
pairs=list(info.items())
print(pairs)

[('a', 1), ('b', 2)]


---

# NumPy

### Question 1: How do you create a 1D NumPy array from a list?

In [17]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


### Question 2: How do you create a 2D array (matrix) of zeros?

In [18]:
zeros=np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Question 3: How do you perform element-wise addition on two arrays?

In [19]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


### Question 4: How do you multiply every element in an array by a scalar?

In [20]:
arr=np.array([10,20,30])
print(arr*2)

[20 40 60]


### Question 5: How do you find the square root of all elements in an array?

In [21]:
arr=np.array([4,9,16])
print(np.sqrt(arr))

[2. 3. 4.]


### Question 6: How do you calculate the mean of a NumPy array?

In [22]:
arr=np.array([10,20,30,40])
print(np.mean(arr))

25.0


### Question 7: How do you create an array with a range of values?

In [23]:
arr=np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


### Question 8: How do you find the maximum value in a NumPy array?

In [24]:
arr=np.array([5,12,7,18])
print(np.max(arr))

18


---

# Matrix Multiplication and Broadcasting

### Question 1: How do you perform matrix multiplication using the dot product?

In [25]:
m1=np.array([[1,2],[3,4]])
m2=np.array([[5,6],[7,8]])
result=np.dot(m1,m2)
print(result)

[[19 22]
 [43 50]]


### Question 2: How do you use the @ operator for matrix multiplication?

In [26]:
m1=np.array([[1,2],[3,4]])
m2=np.array([[5,6],[7,8]])
print(m1@m2)

[[19 22]
 [43 50]]


### Question 3: How do you perform matrix-vector multiplication?

In [27]:
mat=np.array([[1,2],[3,4]])
vec=np.array([10,20])
print(np.matmul(mat,vec))

[ 50 110]


### Question 4: How do you add a scalar to a matrix using broadcasting?

In [28]:
mat=np.array([[1,2],[3,4]])
print(mat+10)

[[11 12]
 [13 14]]


### Question 5: How do you add a 1D array to a 2D array via broadcasting?

In [29]:
mat=np.array([[1,2,3],[4,5,6]])
row=np.array([10,20,30])
print(mat+row)

[[11 22 33]
 [14 25 36]]


### Question 6: How do you broadcast a column vector across a matrix?

In [30]:
mat=np.array([[1,2],[3,4]])
col=np.array([[10],[20]])
print(mat+col)

[[11 12]
 [23 24]]


### Question 7: How do you multiply two arrays of different shapes using broadcasting?

In [31]:
a=np.array([1,2,3])
b=np.array([[10],[20],[30]])
print(a*b)

[[10 20 30]
 [20 40 60]
 [30 60 90]]


### Question 8: How do you calculate the transpose of a matrix?

In [32]:
mat=np.array([[1,2,3],[4,5,6]])
print(mat.T)

[[1 4]
 [2 5]
 [3 6]]
