In [1]:
import numpy as np

In [21]:
a=np.arange(2,20,2)

In [22]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
b=np.linspace(1,20,6)

In [9]:
b

array([ 1. ,  4.8,  8.6, 12.4, 16.2, 20. ])

In [10]:
b.reshape(3,2)

array([[ 1. ,  4.8],
       [ 8.6, 12.4],
       [16.2, 20. ]])

In [23]:
c=np.zeros((3,4))

In [24]:
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
c.itemsize

8

In [35]:
a=np.arange(10)

In [36]:
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.random.choice(a)

np.int64(7)

In [38]:
np.random.random_integers(0,10,4)

C:\Users\Abdullah Azhar\AppData\Local\Temp\ipykernel_17732\3482911836.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  np.random.random_integers(0,10,4)


array([5, 8, 7, 9], dtype=int32)